import ThemeRegistry from "@/components/themeRegistry";
import "./globals.css";
import NavbarLoader from "@/components/NavbarLoader";
import DevHumorDialog from "@/components/DevHumorDialog";

export const metadata = {
  title: "MD.AT - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <DevHumorDialog />
          <NavbarLoader />
          <main>{children}</main>
        </ThemeRegistry>
      </body>
    </html>
  );
}